from django.contrib import admin
from .models import Alumno, Amigo, Carrera, CarreraSede, Chat, Comentario, Comuna, Coordinador, Director, Docente, Encuesta, EstadoPerfil, EventoAgendado, Genero, Institucion, MeGusta, MyAdmin, Participantes, Publicacion, Ramo, RamoDoc, Region, Seccion, SeccionAluDoc, Sede, TipoUsuario, Usuario, UsuarioChat
# Register your models here.

admin.site.register(Alumno)
admin.site.register(Amigo)
admin.site.register(Carrera)
admin.site.register(CarreraSede)
admin.site.register(Chat)
admin.site.register(Comentario)
admin.site.register(Comuna)
admin.site.register(Coordinador)
admin.site.register(Director)
admin.site.register(Docente)
admin.site.register(Encuesta)
admin.site.register(EstadoPerfil)
admin.site.register(EventoAgendado)
admin.site.register(Genero)
admin.site.register(Institucion)
admin.site.register(MeGusta)
admin.site.register(MyAdmin)
admin.site.register(Participantes)
admin.site.register(Publicacion)
admin.site.register(Ramo)
admin.site.register(RamoDoc)
admin.site.register(Region)
admin.site.register(Seccion)
admin.site.register(SeccionAluDoc)
admin.site.register(Sede)
admin.site.register(TipoUsuario)
admin.site.register(Usuario)
admin.site.register(UsuarioChat)
