# Generated by Django 4.2.5 on 2023-09-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id_amistad', models.AutoField(primary_key=True, serialize=False)),
                ('id_amigo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'amigo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarreraSede',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carrera_sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=150)),
                ('archivo', models.BinaryField(blank=True, null=True)),
                ('usu_recep', models.BigIntegerField()),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_coment', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('titulo', models.CharField(max_length=30)),
                ('descrip', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('estado', models.BigIntegerField()),
                ('id_encu', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('op_uno', models.CharField(blank=True, max_length=20, null=True)),
                ('op_dos', models.CharField(blank=True, max_length=20, null=True)),
                ('op_tres', models.CharField(blank=True, max_length=20, null=True)),
                ('op_cuatro', models.CharField(blank=True, max_length=20, null=True)),
                ('op_cinco', models.CharField(blank=True, max_length=20, null=True)),
                ('text_resp_uno', models.CharField(blank=True, max_length=100, null=True)),
                ('text_resp_dos', models.CharField(blank=True, max_length=100, null=True)),
                ('text_resp_tres', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'encuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPerfil',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nom_est', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoAgendado',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_even', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('desc', models.CharField(max_length=150)),
                ('estado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'evento_agendado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_gen', models.AutoField(primary_key=True, serialize=False)),
                ('nom_gen', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id_me_gusta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'me_gusta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'my_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_parti', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publi', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descrip', models.CharField(max_length=150)),
                ('estado', models.BigIntegerField()),
                ('img_vid', models.BinaryField()),
            ],
            options={
                'db_table': 'publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id_ramo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ramo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ramo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_secc', models.AutoField(primary_key=True, serialize=False)),
                ('nom_seccion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sede', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.BigIntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('ap_pater', models.CharField(max_length=30)),
                ('ap_mater', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.BigIntegerField()),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.usuario')),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.usuario')),
            ],
            options={
                'db_table': 'coordinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.usuario')),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.usuario')),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('usuario_id_usuario', models.OneToOneField(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.usuario')),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeccionAluDoc',
            fields=[
                ('seccion_id_secc', models.OneToOneField(db_column='seccion_id_secc', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.seccion')),
            ],
            options={
                'db_table': 'seccion_alu_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioChat',
            fields=[
                ('id_chat', models.OneToOneField(db_column='id_chat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.chat')),
            ],
            options={
                'db_table': 'usuario_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RamoDoc',
            fields=[
                ('docente_id_usuario', models.OneToOneField(db_column='docente_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='socialDuoc.docente')),
            ],
            options={
                'db_table': 'ramo_doc',
                'managed': False,
            },
        ),
    ]
